### ISSUE TITLE
dependencie faild on st-nucleo-f401re

### ISSUE THREAD

**Issue by vahid-sohrabloo** [ARMmbed/mbed-hal-st-stm32f4#10]
mbed-hal-st-stm32f401re module  not in yotta repository

~~~
error: Failed to satisfy dependencies of /home/vahid/blinky/yotta_modules/mbed-hal-st-stm32f4:
error: mbed-hal-st-stm32f401re does not exist in the modules registry. Check that the name is correct, and that it has been published.
~~~

**Comment by 0xc0170** [comment]
The target you are using is not fully supported, as the message indicates - modules are not published. Means the missing modules are not in the registry, neither on ARMmbed github organization. 
Please look at https://github.com/ARMmbed/mbed-os, where is the list of targets supported.

**Comment by vahid-sohrabloo** [comment]
When this target is supported? and how I can help to support this target.

**Comment by rainierwolfcastle** [comment]
http://jira-dev0.cambridge.arm.com/browse/IOTSFW-833

**Comment by rainierwolfcastle** [comment]
ARM Internal Ref: IOTSFW-989

**Comment by hugovincent** [comment]
Hi @vahid-sohrabloo, hopefully that target will be supported soon, but we don't currently have a timeframe for it.

**Comment by 0xc0170** [comment]
@vahid-sohrabloo This should be resolved. If this persists, reopen the issue or report a new one.
